version: '3.4'



services:
  dgt.redis.api:
    image: dgt.redis.api
    build:
      context: ./Dgt.Redis.Api
      dockerfile: Dockerfile
    ports:
      - "8544:80" # change this to whatever port you want to expose
      - "8543:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=DevForEver
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/devdocker.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - redis
      - cassandra
      - seq
  dgt.redis.front:
    image: dgt.redis.front
    build:
      context: ./Dgt.Redis.Front
      dockerfile: Dockerfile
    ports:
      - "8554:80" # change this to whatever port you want to expose
      - "8553:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=DevForEver
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/devdocker.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - dgt.redis.api
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
